skinparam roundcorner 10
skinparam BoxPadding 10
skinparam headerFontColor #BD10E0
skinparam headerFontSize 18
skinparam sequence {
  ArrowColor #BD10E0
  GroupBackgroundColor #BD10E0
  GroupBorderColor #EDECFF
  GroupHeaderFontColor #ffffff
  BoxBorderColor #BD10E0
  BoxBackgroundColor #EDECFF
  BoxPadding 10

  ParticipantBorderColor #BD10E0
  ParticipantBackgroundColor #ffffff
  ParticipantPadding 10

  ActorBorderColor #BD10E0
  ActorBackgroundColor #ffffff
  EntityBorderColor #BD10E0
  EntityBackgroundColor #ffffff
  DatabaseBorderColor #BD10E0
  DatabaseBackgroundColor #ffffff

  LifeLineBorderColor #878787
}

