@startuml
!include ../gluonskin.plantuml
hide footbox
title Alice uses ETH to send THX tokens to Bob 
actor Alice
box "Gluon Token"
  participant "Smart Contract" as GluonSC
  participant "Funding Pool" as FundingPool
  participant "ETH Pool" as ETHPool
end box
box "Thanx Token"
  participant "Smart Contract" as ThanxSC
  participant "GLU Pool" as THXGLUPool
end box
actor Bob

Alice -> GluonSC : Sends 0.001 ETH
GluonSC -> FundingPool : Tx Fee 0.01 % ETH
GluonSC -> ETHPool : Stakes 0.0009999 ETH
GluonSC -> ThanxSC : Mints 10 GLU
ThanxSC -> THXGLUPool : Stakes 10 GLU
ThanxSC -> Bob : Mints 500 THX

@enduml
