@startuml
!include ../gluonskin.plantuml
hide footbox
title Alice uses ETH to create THX tokens and sends them to Bob 
actor Alice #E03F10
box "Gluon Token"
  participant "Smart Contract" as GluonSC
  participant "ETH Pool" as ETHPool
end box
box "Gluon Token Factory"
  participant "Smart Contract" as GluonFactorySC
end box
box "Thanx Token"
  participant "Smart Contract" as ThanxSC
  participant "GLU Pool" as THXGLUPool
end box
actor Bob #1051E0

Alice -> GluonSC : Sends 0.001 ETH
GluonSC -> ETHPool : Stakes 0.0009999 ETH
GluonSC -> GluonSC : Mints 10 GLU
GluonSC -> GluonFactorySC : Creates token (+ 10 GLU)
GluonFactorySC -> ThanxSC : Sends 10 GLU

ThanxSC -> THXGLUPool : Stakes 10 GLU
ThanxSC -> Bob : Mints 500 THX

@enduml
