@startuml
!include ../gluonskin.plantuml
hide footbox
title Alice uses GLU to create THX tokens
actor Alice #E03F10
box "Gluon Token Factory"
  participant "Smart Contract" as GluonFactorySC
end box
box "Thanx Token"
  participant "Smart Contract" as ThanxSC
  participant "GLU Pool" as THXGLUPool
end box

Alice -> GluonFactorySC : Creates token (+ 10 GLU)
GluonFactorySC -> GluonFactorySC : Creates Thanx Token
GluonFactorySC -> ThanxSC : Sends 10 GLU

ThanxSC -> THXGLUPool : Stakes 10 GLU
ThanxSC -> Alice : Mints 500 THX

@enduml
