@startuml
!include ../gluonskin.plantuml
hide footbox
title Alice sends THX to Bob
actor Alice #E03F10
box "Thanx Token"
  participant "Smart Contract" as ThanxSC
end box
actor Bob #1051E0

Alice -> ThanxSC : Sends 500 THX
ThanxSC -> Bob : Sends 500 THX

@enduml
