@startuml
!include ../gluonskin.plantuml
hide footbox
title Alice uses USD to send THX tokens to Bob 
actor Alice #E03F10
box "3rd Party Exchange" #F5E9D7
  participant "API" as Exchange
end box
box "Gluon Token"
  participant "Smart Contract" as GluonSC
  participant "Funding Pool" as FundingPool #9CEF9F
  participant "ETH Pool" as ETHPool
end box
box "Thanx Token"
  participant "Smart Contract" as ThanxSC
  participant "GLU Pool" as THXGLUPool
end box
actor Bob #1051E0

Alice -> Exchange : Sends 10 USD
Exchange -> Exchange : Takes 0.10 USD Fee
Exchange -> GluonSC : Converts to 0.001 ETH
GluonSC -> FundingPool : Tx Fee 0.01 % ETH
GluonSC -> ETHPool : Stakes 0.0009999 ETH
GluonSC -> ThanxSC : Mints 10 GLU
ThanxSC -> THXGLUPool : Stakes 10 GLU
ThanxSC -> Bob : Mints 500 THX

@enduml
