@startuml
!include ../gluonskin.plantuml
hide footbox
title Bob exchanges THX to USD
actor Bob #1051E0
box "Thanx Token"
  participant "Smart Contract" as ThanxSC
  participant "GLU Pool" as THXGLUPool
end box
box "Gluon Token"
  participant "Smart Contract" as GluonSC
  participant "ETH Pool" as ETHPool
end box
box "3rd Party Exchange" #F5E9D7
  participant "API" as Exchange
end box

Bob -> ThanxSC : Burns 500 THX
ThanxSC <- THXGLUPool : Takes 10 GLU
ThanxSC -> GluonSC : Burns 10 GLU
GluonSC <- ETHPool : Takes 0.001 ETH
GluonSC -> Exchange : Sends 0.001 ETH
Exchange -> Exchange : Takes 0.10 USD Fee
Exchange -> Bob : Converts 8.9 USD

@enduml
