@startuml
!include ../gluonskin.plantuml
hide footbox
title Bob exchanges THX to LOV
actor Bob
box "Thanx Token"
  participant "Smart Contract" as ThanxSC
  participant "GLU Pool" as THXGLUPool
end box
box "Gluon Token"
  participant "Smart Contract" as GluonSC
end box
box "Love Token"
  participant "Smart Contract" as LoveSC
  participant "GLU Pool" as LOVGLUPool
end box

Bob -> ThanxSC : Burns 500 THX
ThanxSC <- THXGLUPool : Takes 10 GLU
ThanxSC -> GluonSC : Burns 10 GLU
GluonSC -> LoveSC : Sends 10 GLU
LoveSC -> LOVGLUPool : Stakes 10 GLU
LoveSC -> Bob : Mints 600 LOV

@enduml
